(atom? 'atom)
(atom? 'turkey)
(atom? 1492)
(atom? 'u)
(atom? '*abc$)
(list? '(atom))
(list? '(atom turkey or))
(list? 'f(atom turkey) or)
(restart 1)
(list? '((atom turkey) or))
(sexpr? 'xyz)
(sexpr? '(x y z))
(sexpr? '((x y) z))
(list? '(how are you doing so far))
(length '(how are you doing so far))
(list? '(((how) are) ((you) (doing so)) far))
(length '(((how) are) ((you) (doing so)) far))
(list? ())
(atom? ())
(list? '(()()()()))
(let ((l '(a b c))) (car l))
(let ((l 'hotdog)) (car l))
(restart 1)
(let ((l ())) (car l))
(restart 1)

;; The Law of Car

(let ((l '(((hotdogs)) (and) (pickle) (relish))))
  (car l))
(let ((l '(((hotdogs)) (and) (pickle) (relish))))
  (car (car l)))
(let ((l '(a b c)))
  (cdr l))
(let ((l '((a b c) x y z)))
  (cdr l))
(let ((l '(hamburger)))
  (cdr l))
(let ((l '((x) t r)))
  (cdr l))
(let ((a 'hotdogs))
  (cdr a))
(restart 1)
(let ((l ())) (cdr l))
(restart 1)

;; The Law of Cdr

(let ((l '((b) (x y) ((c)))))
  (car (cdr l)))
(let ((l '((b) (x y) ((c)))))
  (cdr (cdr l)))
(let ((l '(a (b (c)) d)))
  (cdr (car l)))
(restart 1)
(let ((a 'penut) (l '(butter and jelly)))
  (cons a l))
(let ((s '(banana and)) (l '(peanut butter and)))
  (cons s l))
(let ((s '((help) this)) (l '(is very ((hard) to learn))))
  (cons s l))
(let ((s '(a b (c))) (l ()))
  (cons s l))
(let ((s 'a) (l ()))
  (cons s l))
(let ((s '((a b c))) (l 'b))
  (cons s l)) ;; results in pair (((a b c)) . b)
(let ((s 'a) (l 'b))
  (cons s l)) ;; results in pair (a . b)

;; The Law of Cons

(let ((s 'a) (l '((b) c d)))
  (cons s (car l)))
(let ((s 'a) (l '((b) c d)))
  (cons s (cdr l)))
(null? ())
(null? '())
(let ((l '(a b c)))
  (null? l))
(let ((a 'spaghetti))
  (null? a))

;; The Law of Null?

(let ((s 'Harry))
  (atom? s))
(let ((s '(Harry had a heap of apples)))
  (atom? s))
(let ((l '(Harry had a heap of apples)))
  (atom? (car l)))
(let ((l '(Harry had a heap of apples)))
  (atom? (cdr l)))
(let ((l '(Harry)))
  (atom? (cdr l)))
(let ((l '(swing low sweet cherry oat)))
  (atom? (car (cdr l))))
(let ((l '(swing (low sweet) cherry oat)))
  (atom? (car (cdr l))))
(let ((a1 'Harry) (a2 'Harry))
  (eq? a1 a2))
(let ((a1 'margarine) (a2 'butter))
  (eq? a1 a2))
(let ((l1 ()) (l2 '(strawberry)))
  (eq? l1 l2))
(let ((n1 6) (n2 7))
  (eq? n1 n2))

;; The Law of Eq?

(let ((l '(Mary had a little lamb chop)) (a 'Mary))
  (eq? (car l) a))
(let ((l '(soured milk)) (a 'milk))
  (eq? (cdr l) a))
(let ((l '(beans beans we need jelly beans)))
  (eq? (car l) (car (cdr l))))
